"""posts table

Revision ID: 7126629b4734
Revises: 104c914d3380
Create Date: 2021-07-13 16:24:37.631528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7126629b4734'
down_revision = '104c914d3380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('dl1rm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('user', sa.Column('bench1rm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('user', sa.Column('squat1rm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('user', sa.Column('press1rm', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'press1rm')
    op.drop_column('user', 'squat1rm')
    op.drop_column('user', 'bench1rm')
    op.drop_column('user', 'dl1rm')
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'confirmed_on')
    op.drop_column('user', 'confirmed')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
